version: "3"

services:

  kanboard:
    image: kanboard/kanboard:latest
    restart: on-failure
    ports:
     - "3004:80"
    volumes:
     - "/var/docker/kanboard/data:/var/www/app/data"
     - "/var/docker/kanboard/plugins:/var/www/app/plugins"
    networks:
      - internal

networks:
    internal:
      driver: bridge

