version: "3"

services:

  monitoringdb:
    image: influxdb
    restart: on-failure
    expose:
      - "8086"
    environment:
      INFLUXDB_DB: cadvisor     
    volumes:
      - /var/docker/monitoring/influxdb/data:/var/lib/influxdb
    networks:
      - internal

  cadvisor:
    image: google/cadvisor
    restart: on-failure
    ports:
      - "3000:8080"
    hostname: '{{.Node.Hostname}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=monitoringdb:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - monitoringdb
    networks:
      - internal

  chronograf:
    image: chronograf
    ports:
      - "3001:8888"
    volumes:
      - /var/docker/monitoring/chronograf/data:/var/lib/chronograf
    depends_on:
      - monitoringdb
    networks:
      - internal
      
  grafana:
    image: grafana/grafana
    restart: on-failure
    ports:
      - "3002:3000"
    volumes:
      - /var/docker/monitoring/grafana/data:/var/lib/grafana
    depends_on:
      - monitoringdb
    networks:
      - internal

networks:
    internal:
      driver: bridge
