version: '3'

services:

  mongodb:
    image: mongo
    restart: on-failure
    command: mongod --smallfiles --oplogSize 128
    expose:
      - "27017"
    volumes:
      - "/var/docker/wikijs/mongodb/data:/data/db"
      - "/var/docker/wikijs/mongodb/dump:/dump"
    networks:
      - internal

  wikijs:
    image: requarks/wiki
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "3005:80"
    environment:
      WIKI_JS_HEROKU: 1
      WIKI_ADMIN_EMAIL: email@company.com
    volumes:
      - "/var/docker/wikijs/wikijs/logs:/logs"
      - "/var/docker/wikijs/wikijs/data:/var/www/wiki/data"
      - "/var/docker/wikijs/wikijs/repo:/var/www/wiki/repo"
      - "/var/docker/wikijs/wikijs/keys:/etc/wiki/keys"
      - "./config.yml:/var/wiki/config.yml"
    networks:
      - internal

networks:
    internal:
      driver: bridge

