version: "3"

services:

  postgres:
    image: postgres
    restart: on-failure
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
      - SERVICE_NAME=gogs-postgres
    volumes:
      - "/var/docker/gogs/postgres/data:/var/lib/postgresql"
    networks:
      - internal

  gogs:
    image: gogs/gogs
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "3003:3000"
      - "2222:22"
    volumes:
      - "/var/docker/gogs/app/data:/data"
    networks:
      - internal

networks:
    internal:
      driver: bridge
